# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 34fc10bd22123dc08931ec18840f5f8d99a6c7984d38224dc9145f178ff9c1aaccd7e8ee9e72e443064d62717b67df19c844338e63447baf21bf477d146733ba

test:
  secret_key_base: e9069aa5d337c7d8425f58539fb7e687638b10a9eac93e62201ab963e89a73c41802bf181b63feb6ee33a93576a2eed258123553b7231d7ba36907931c448e5e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
